[toolchain]

[features]
resolution = false
skip-lint = false

[programs.localnet]
program-b = "6ZhfnambHxuUe9N3N7gRgvwmaBpdxkZgy3aYq5vhMP52"
program_a = "9X1Tp9DqSwtAANKk2vU5qn1okYU3ED4x14jHmqjC1Ghb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
